export const products = [
  {
    id: 1,
    title: "Banana",
    description: "In Pieces",
    price: "10",
    img: "/uploads/banana1.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "Mango",
    description: "In Kg",
    price: "230",
    img: "/uploads/mango.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "Watermelon",
    description: "In Kg",
    price: "3500",
    img: "/uploads/watermelon.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "strawberry",
    description: "In Kg",
    price: "90500",
    img: "/uploads/strawberry.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "flourall",
    description: "Pure and fresh",
    price: "2500",
    img: "/uploads/flourall.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "floursplet",
    description: "Pure and fresh",
    price: "3500",
    img: "/uploads/floursplet.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Samsung S21",
    description: "jet Black",
    price: "2500",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 8,
    title: "Iphone 11",
    description: "Available in diffrent colors",
    price: "90500",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "Samsung A Series",
    description: "J Series J1 J2... ",
    price: "2500",
    img: "/uploads/m1.jpg",
    quantity: 1,
  },
];
